services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=myrhdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    container_name: 'database'

